server:
  port: 10086
eureka:

  instance:
    hostname: eureka1
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka2:10087/eureka/
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000
