spring:
  application:
    name: itemservice
#  cloud:
#    config:
#      override-none: true
  profiles:
    active: Item8002


#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka1:10086/eureka, http://eureka2:10087/eureka
###
##management:
##  endpoints:
##    web:
##      exposure:
##        include: hystrix.stream
#
#---
#spring:
#  profiles:
#    active: Item8002
#
server:
  port: 8002
#---
#spring:
#  profiles:
#    active: Item8003
#
#server:
#  port: 8003
