#spring:
#  application:
#    name: itemservice
spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: item-service
      profile: dev

##server:
##  port: 8002
##
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:10086/eureka, http://eureka2:10087/eureka
##
##management:
##  endpoints:
##    web:
##      exposure:
##        include: hystrix.stream
#
---
spring:
  profiles: Item8002

server:
  port: 8002
---
spring:
  profiles: Item8003

server:
  port: 8003
