spring:
  application:
    name: userservices
  datasource:
    url: jdbc:mysql://localhost:3306/bio01?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:10086/eureka,http://eureka2:10087/eureka
#续约更新
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 2
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    database: 6
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
      max-wait: -1
      min-idle: 0
      timeout: 1200




mybatis:
  mapper-locations: classpath:/mapping/*.xml
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true

server:
  port: 8011

