spring:
  application:
    name: zuul

server:
  port: 3001
main:
  allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:10086/eureka, http://eureka2:10087/eureka
uul:
  retryable: true
  sensitive-headers:

#zuul:
#  routes:
#    itemservice: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**
zuul:
  routes:
   sso-server.path: /sso-server/**
   sso-server.service-id: sso-server


  host.socket-timeout-millis: 60000
  host.connect-timeout-millis: 10000
  #Zuul丢失Cookie的解决方案：https://blog.csdn.net/lindan1984/article/details/79308396
  sensitive-headers:

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


